version: "3.7"
networks:
  localnetwork:
services:
  job:
    container_name: job
    build:
      context: ./
      dockerfile: docker/cronjob/Dockerfile
    image: dsp8ef9/bookprices_job:latest
    volumes:
      - ./docker/cronjob/log:/usr/local/bookprices_job/log
      - ./docker/cronjob/config:/usr/local/bookprices_job/config
      - ./docker/cronjob/images:/usr/local/bookprices_job/images
    networks:
      - localnetwork
  web:
    container_name: web
    build: 
      context: ./
      dockerfile: docker/web/Dockerfile
    image: dsp8ef9/bookprices_web:latest
    env_file: ./docker/web/.web.env
    networks:
      - localnetwork
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    image: dsp8ef9/bookprices_nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/cronjob/images:/usr/share/nginx/html/static/images/books:ro
      - ./bookprices/web/assets:/usr/share/nginx/html/static/assets:ro
    depends_on:
      - web
    networks:
      - localnetwork
  db:
    container_name: db
    image: mysql:8.0.33
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file: ./docker/db/.db.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - localnetwork