version: "3.7"
networks:
  localnetwork:
services:
  price_update:
    build:
      context: ./
      dockerfile: docker/cronjobs/Dockerfile
    image: dsp8ef9/book_prices_update:latest
    volumes:
      - ./docker/cronjobs/log:/usr/local/book_prices/cronjobs/log
      - ./docker/cronjobs/config:/usr/local/book_prices/cronjobs/config
    networks:
      - localnetwork
  web:
    build: 
      context: ./
      dockerfile: docker/web/Dockerfile
    image: dsp8ef9/book_prices_web:latest
    env_file: ./docker/web/.web.env
    ports:
      - "8080:80"
    networks:
      - localnetwork
  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file: ./docker/db/.db.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - localnetwork