networks:
  localnetwork:
services:
  job:
    container_name: job
    profiles:
      - default
    build:
      context: ./
      dockerfile: docker/jobrunner/Dockerfile
    image: dsp8ef9/bookprices_jobrunner:latest
    env_file: ./docker/jobrunner/.jobrunner.env
    volumes:
      - ./docker/jobrunner/logs:/app/logs
      - ./docker/jobrunner/images:/app/images
    networks:
      - localnetwork
  web:
    container_name: web
    profiles:
      - default
    build: 
      context: ./
      dockerfile: docker/web/Dockerfile
    image: dsp8ef9/bookprices_web:latest
    env_file: ./docker/web/.web.env
    volumes:
      - ./google_client_secrets.json:/usr/local/bookprices_web/google_client_secrets.json:ro
    networks:
      - localnetwork
  nginx:
    container_name: nginx
    profiles:
      - default
    restart: always
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    image: dsp8ef9/bookprices_nginx:latest
    env_file: ./docker/nginx/.nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/tls:/etc/nginx/tls:ro
      - ./docker/cronjob/images:/usr/share/nginx/html/static/images/books:ro
    depends_on:
      - web
    networks:
      - localnetwork
  job_api:
    container_name: job_api
    profiles:
      - default
    image: dsp8ef9/bookprices_jobapi:latest
    env_file: docker/job_api/.job_api.env
    ports:
      - "8080:8080"
    networks:
      - localnetwork
  db:
    container_name: db
    profiles:
      - default
      - db_only
    image: mysql:8.4.0
    command: --mysql-native-password=ON
    restart: always
    env_file: ./docker/db/.db.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/config/my.cnf:/etc/my.cnf:ro
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - localnetwork
  redis:
    container_name: redis
    profiles:
      - default
      - db_only
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    networks:
      - localnetwork